### PR TITLE
Add option to use custom surrogate training implementations

### PR DESCRIPTION
**Pull request by frthjf**
This allows for experimentation with custom surrogate training options such as training on the constraint information. Wiring up the `file_path` also allows for checkpointing and other file operations.

### CODE REVIEW

**Comment by iraikov** [comment]
Is there an example for this? I don't quite understand how it is different than a custom surrogate method.

**Comment by frthjf** [comment]
This is to override the [train() method here](https://github.com/iraikov/dmosopt/blob/main/dmosopt/MOASMO.py#L389), so it's more generic than just changing the model. Most notably, the surrogate method does not have access to the feasibility/constraint data but only receives filtered solutions. With this new option you can change that, for example:

```diff
+def my_custom_surrogate_training(
    nInput,
    nOutput,
    xlb,
    xub,
    Xinit,
    Yinit,
    C,
    surrogate_method_name="gpr",
    surrogate_method_kwargs={},
    logger=None,
    file_path=None,
):
    x = Xinit.copy()
    y = Yinit.copy()

+   if surrogate_method_kwargs.get('filter_feasible', True) and C is not None:
-   if C is not None:
        feasible = np.argwhere(np.all(C > 0.0, axis=1))
        if len(feasible) > 0:
            feasible = feasible.ravel()
            x = x[feasible, :]
            y = y[feasible, :]
            if logger is not None:
                logger.info(f"Found {len(feasible)} feasible solutions")

    x, y = MOEA.remove_duplicates(x, y)

    # resolve shorthands
    if surrogate_method_name in default_surrogate_methods:
        surrogate_method_name = default_surrogate_methods[surrogate_method_name]

    surrogate_method_cls = import_object_by_path(surrogate_method_name)
    sm = surrogate_method_cls(
        x,
        y,
        nInput,
        nOutput,
        xlb,
        xub,
        **surrogate_method_kwargs,
        logger=logger,
    )

+  sm.learn_from_constraints(C)

    return sm
```

I guess one alternative would be to push the constraint and duplicate handling down into the `surrogate_method_cls` but that would require some refactoring of all the surrogate models.

**Comment by frthjf** [comment]
On second thought, it might make more sense to refactor this with the training of the feasibility model, which is currently hard-coded and happens [right before the training of the surrogate model](https://github.com/iraikov/dmosopt/blob/main/dmosopt/MOASMO.py#L238) and seems somewhat redundant.

**Comment by iraikov** [comment]
It is not a bad idea to factor our the feasibility model. But if we figure out some way for combined training of surrogate and feasibility, we might need a custom training procedure, indeed.

**Comment by frthjf** [comment]
Yes, let me experiment around a bit to see what API would cover these use cases.

**Comment by frthjf** [comment]
I've generalized it now so that one can override the model for the objective (i.e. surrogate model), the feasibility model, and the sensitivity model. It's mix and match, including one model to rule them all, for example:
```python
from dmosopt.model import Model

# only override the feasibility model
def custom_model(Xinit, Yinit, C, xlb, xub, file_path, options):
    my_feasibility_model = ...
    return Model(feasibility=my_feasibility_model)

# override everything with unified model
def custom_model2(Xinit, Yinit, C, xlb, xub, file_path, options):
    grand_unified_theory_of_everything_model = ...
    return Model(
          objective=grand_unified_theory_of_everything_model , 
          feasibility=grand_unified_theory_of_everything_model ,  
          sensitivity=grand_unified_theory_of_everything_model 
    )
```

**Review by iraikov — APPROVED** [review]

**Pull request merged**
